export const ADD_RIDER = 'ADD_RIDER'
export const CHANGE_DEST = 'CHANGE_DEST'
export const SWITCH_DRIVE = 'SWITCH_DRIVE'
export const SET_DATE = 'SET_DATE'
export const PICK_IMAGE = 'PICK_IMAGE'
export const TRY_AUTH = 'TRY_AUTH'
export const AUTH_SET_TOKEN = 'AUTH_SET_TOKEN'